-- HiMu seed data
-- Runs after migrations on `supabase db reset`.
--
-- No content is seeded via SQL. DJs, tracks, covers, avatars and playlists are
-- produced by the AI generation pipeline in scripts/generate/. After a reset:
--
--   npm run gen:seed        # DJs + generation configs
--   npm run gen:avatars     # DJ avatars (flux, free)
--   npm run gen:covers      # AI Mixes hero + playlist covers (flux, free)
--
-- Then, once Cloudflare billing is enabled (paid music model):
--
--   npm run gen:music       # instrumental tracks + per-track covers
--   npm run gen:cleanup     # remove any leftover placeholders
--   npm run gen:playlists   # public playlists from the generated tracks
